[package]
name = "ant-releases"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Download and unpack binaries released from the safe_network repository"
license = "GPL-3.0"
version = "0.4.1"
edition = "2021"
repository = "https://github.com/maidsafe/ant-releases"

[dependencies]
async-trait = "0.1"
chrono = "0.4.26"
flate2 = "1.0"
lazy_static = "1.4.0"
regex = "1.10.2"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
semver = "1.0.22"
serde_json = "1.0"
tar = "0.4.40"
thiserror = "1.0.49"
tokio = { version = "1.26", features = ["full"] }
zip = "0.6.6"

[dev-dependencies]
assert_fs = "~1.0"
predicates = "2.0"
